title: Eric Martínez
email: contacto@ericmartinezf.com
description: Ingeniero Informático, aficionado por los deportes y el aprendizaje continuo.
# this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Eric Martínez # add your name
author-pic:
about-author: Ingeniero Informático, aficionado por los deportes y el aprendizaje continuo.

# Contact links
email: contacto@ericmartinezf.com # Add your Email address
phone: # Add your Phone number
website: https://ericmartinezf.com # Add your website, do not add http://
linkedin: ericmartinezf # Add your Linkedin handle
github: ericmartinezf # Add your Github handle
twitter: '@ericmartinezf' # Add your Twitter handle
facebook: ericmartinezf # Add your Facebook handle
instagram: ericmartinezf # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: ericmartinezf # Add your discus identifier

# Tracker
analytics: UA-115466682-1 # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
